version: "3.7"

networks:
  db-net:
  api-net:

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${COMPOSE_SQL_PASSWORD}
      POSTGRES_DB: ${COMPOSE_SQL_DB}
    networks:
      - db-net
  bot:
    build:
      dockerfile: bot.Dockerfile
    depends_on:
      - api
    restart: unless-stopped
    ports:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_PATH: /var/log/bot
    networks:
      - api-net
    volumes:
      - ${LOG_PATH}:/var/log/bot
  api:
    build:
      dockerfile: api.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${API_PORT}:80
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_PORT: 80
      LOG_PATH: /var/log/bot
      API_HOST: ${API_HOST}
      GIN_MODE: release
      CORS_ORIGINS: ${CORS_ORIGINS}
      SECURE_COOKIE: ${SECURE_COOKIE}
    networks:
      - db-net
      - api-net
    volumes:
      - ${LOG_PATH}:/var/log/bot
